# Generated by Django 4.1.3 on 2022-11-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_categorias', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_cover', models.ImageField(upload_to='')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('categorias', models.ManyToManyField(to='products.category')),
            ],
        ),
    ]
