# Generated by Django 4.1.3 on 2022-11-20 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_review_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.RenameField(
            model_name='review',
            old_name='comment',
            new_name='product',
        ),
    ]
