# Generated by Django 4.1.3 on 2022-11-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_review_options_rename_comment_review_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='product_categorias',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
